version: '3'
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_PORT}:2000"
    depends_on:
      - mongodb
    env_file:
      - .env
  mongodb:
    image: mongo:4.4.5
    restart: always
    ports:
      - "27017"
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - .env